config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'
  get 'pages/superman'
  get 'pages/batman_vs_superman'

  post 'pages/user_vote_batman'

  post 'pages/user_vote_superman'

  root 'pages#batman_vs_superman'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voter_batman.rb
class VoterBatman < ApplicationRecord
end

app/models/voter_superman.rb
class VoterSuperman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
  	render layout: "bootstrap"
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def batman
  end

  def superman
  end

  def batman_vs_superman
  end

  def user_vote_batman
  	VoterBatman.new(name: params[:name], email: params[:email]).save
  	redirect_to pages_batman_vs_superman_path, notice_bat:"El usuario ha votado por Batman"	
  end

   def user_vote_superman
  	VoterSuperman.new(name: params[:name], email: params[:email]).save
  	redirect_to pages_batman_vs_superman_path, notice_sup:"El usuario ha votado por Superman"	
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<h1>Experiments#page1</h1>
<p>Find me in app/views/experiments/page1.html.erb</p>

<img src="<%= asset_path Apache_Heli.jpg" %>">

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<p>Find me in app/views/experiments/page3.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
  

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/batman.html.erb
<div class="jumbotron">

<h1>I'm Batman!!</h1>
<p>Find me in app/views/pages/batman.html.erb</p>
</div>

<script>
$.backstretch("http://www.planwallpaper.com/static/images/maxresdefault_pzfcoB9.jpg")
</script>

app/views/pages/batman_vs_superman.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>

<p><%= flash[:notice_bat] %> </p>
<p><%= flash[:notice_sup] %> </p>
<h1>Batman VS Superman</h1>
<p>Find me in app/views/pages/batman_vs_superman.html.erb</p>

<body>
<section>
	
		<img src="http://www.planwallpaper.com/static/images/2891179-batman-arkham_knight-review_nologo_20150618.jpg">

		<a href= "<%= pages_batman_url %>"><b>Batman</b>
		</a>

		<form action="<%= pages_user_vote_batman_path %>" method="POST">
			<input name="name">
			<input email="email">
			<input type="submit" value="Enviar">
		</form>

</section>

<section>
	

		<img src="http://static.srcdn.com/wp-content/uploads/Superman-3D-Art.jpg">

		<a href= "<%= pages_superman_url %>"><b>Superman</b>
		</a>

		<form action="<%= pages_user_vote_superman_path %>" method="POST">
			<input name="name">
			<input email="email">
			<input type="submit" value="Enviar">
		</form>

</section>

<%= yield %>

</body>
</html>

app/views/pages/superman.html.erb
<div class="jumbotron">

<h1>This looks like a job for Superman!!</h1>
<p>Find me in app/views/pages/superman.html.erb</p>
</div>

<script>
	$.backstretch("http://static.srcdn.com/wp-content/uploads/Superman-3D-Art.jpg")
</script>